version: "3"

services: 
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "backlog"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: "root"

    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-e", "select 1"]
      interval: 5s
      timeout: 1s
      retries: 10
    volumes:
      - my-app-mysql-data:/var/lib/mysql
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - my-app-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  web:
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mysql
      - elasticsearch
    volumes:
      - .:/my-app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/my-app/node_modules
    ports:
      - "3000:3000"
    environment: 
      RAILS_ENV: development
      MYSQL_HOST: client_backlog_mysql_1
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ""
volumes: 
  gem_cache:
  node_modules:
  my-app-mysql-data:
  my-app-elasticsearch-data: