default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: root
  password: ""

development:
  <<: *default
  database: backlog

test:
  <<: *default
  database: backlog_test

production:
  <<: *default
  database: backlog_production
