default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "127.0.0.1" } %>
  username: <%= ENV.fetch("MYSQL_USERNAME") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "" } %>

development:
  <<: *default
  database: backlog

test:
  <<: *default
  database: backlog_test

production:
  <<: *default
  database: backlog_production
